### ISSUE TITLE
Implement state machines for players and connections

### ISSUE THREAD

**Issue by 46bit** [sirpent-team/sirpent-rust#23]
This will greatly reduce the spaghetti code. In other languages this would have been in the original implementation; unfamiliarity with Rust meant the code only really allows for them now.

A start on one for player has been made. @nemild suggested multiple levels of state machine: one for a connected player in general and one for a player playing a particular game.

* [`sirpent-spec/state-machines.txt`](https://github.com/sirpent-team/sirpent-rust/blob/fe1f86ab52a47efc38b78063087da8cddc332220/sirpent-spec/state-machines.txt#L41) lays out what these might look like. 
* [PlayerState](https://github.com/sirpent-team/sirpent-rust/blob/fe1f86ab52a47efc38b78063087da8cddc332220/src/player.rs#L86) is an experiment in coding this based upon [I-Imvp on Reddit](https://www.reddit.com/r/rust/comments/57ccds/pretty_state_machine_patterns_in_rust/d8rhwq4/).

@Hoverbear's post on [Rust State Machine Patterns](https://hoverbear.org/2016/10/12/rust-state-machine-pattern/) has been a big help in understanding what Rustic state machines can look like. Thanks!

**Comment by Hoverbear** [comment]
Thanks for the shout out! Let me know if I can help. :)
