### ISSUE TITLE
Normal client-server model

### ISSUE THREAD

**Issue by Taneb** [sirpent-team/sirpent-rust#3]
Have clients connect. We tell the server what games to run; a connecting player is sent the current specification and asked if they want to play in the next game.

**Comment by 46bit** [comment]
At present the specification has message lengths be sent across the socket before the actual JSON payload:

``` json
62 {
  "name": "drogon",
  "secret": "D50gOmol310982laskhdasdj"
}72 {
  "sirpent": {
    "version": "0.1.0",
    "msg": "player_accepts"
  }
}
```

This works and is very much what I'd do on an embedded system. However JSON is a structured format. In some languages you can have a JSON deserialiser read from a stream until the JSON fully-parses. I think it better to take that approach, if `serde` will support it in Rust and support in other languages really is there.

The result would be just sending this down the stream:

``` json
{
  "name": "drogon",
  "secret": "D50gOmol310982laskhdasdj"
}{
  "sirpent": {
    "version": "0.1.0",
    "msg": "player_accepts"
  }
}
```
