### ISSUE TITLE
Separate tilings and grid shapes

### ISSUE THREAD

**Issue by Taneb** [sirpent-team/sirpent-rust#5]

**Comment by 46bit** [comment]
For now[1] choice of tiling is implemented as a compile-time option, and there is no distinction between Grids and Tilings. This is not a priority to fix. @qlkzy suggested treating everything as a Graph (at least externally), which does have its appeal.

[1] https://github.com/sirpent-team/sirpent-rust/commit/bd1f76ebc81d490b521df3b116f4cfd3c2d7b2cd

**Comment by 46bit** [comment]
For now I think we're fine as things are. We can revisit this later if problems come up.
