### ISSUE TITLE
Optimize collision detection

### ISSUE THREAD

**Issue by Taneb** [sirpent-team/sirpent-rust#7]

**Comment by 46bit** [comment]
Back in September, @Taneb [implemented](https://github.com/sirpent-team/sirpent-rust/commit/9c7af523ffcff2ae1c98fa55d9155ca5d54fb083) optimised "_has snake A has collided with snake B?_" collision detection code.

Sirpent-rust is now actually working, albeit with no Grid-bounds detection! The above-mentioned method is [used in a simple fashion](https://github.com/sirpent-team/sirpent-rust/blob/26e8e05b751c73f15ee70a2c7eadca5e77f9061f/src/game_state.rs#L106): O(n²) where n is the number of snakes.

This should suffice for now. 👍
